[package]
name = "server_login"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { path = "../database" }
tide = "0.16"
async-std = { version = "1.8", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }